name = "AutoSymPTR"
uuid = "78a0c066-08f1-49a8-82f0-b29cd485e1d3"
authors = ["lxvm <lorenzo@vanmunoz.com>"]
version = "0.3.1"

[deps]
ChunkSplitters = "ae650224-84b6-46f8-82ea-d812ca08434e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ChunkSplitters = "1, 2"
StaticArrays = "1"
julia = "1.6"

[extras]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["FFTW", "Test"]
